### ISSUE TITLE
Kaltura installation error

### ISSUE THREAD

**Issue by erkanyetik26** [kaltura/installer#36]
# rpm-ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
# yum install Kaltura server

http://installrepo.kaltura.org/releases/latest/RPMS/noarch/repodata/96896afb45754dbfb151dad5ada5a105ade1f2b74547f69b4a8fd09c73c305fc-primary.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.

Please help 

Regards

**Comment by kaltura-hooks** [comment]
Hi @erkanyetik26,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by erkanyetik26** [comment]
Centos 6.8 ,CE kaltura, i am using guide on this link.   
(https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#ssl-step-by-step-installation)

After yum install Kaltura server command i see this error.

http://installrepo.kaltura.org/releases/latest/RPMS/noarch/repodata/96896afb45754dbfb151dad5ada5a105ade1f2b74547f69b4a8fd09c73c305fc-primary.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
 Thanks for help.

**Comment by jessp01** [comment]
Hi @erkanyetik26, 
I imagine it was a temporary issue with your CDN edge. Closing this one but if you're still having problems, please post them on forum.kaltura.org.
For bug reports about the installation, please open an issue here: https://github.com/kaltura/platform-install-packages/
This repo is deprecated.

Thanks,
